[theme]
primaryColor        = "#16a34a"
backgroundColor     = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor           = "#1e293b"
font                = "sans serif"

[server]
headless            = true
enableCORS          = true
enableXsrfProtection = true

[logger]
level = "error"

[browser]
gatherUsageStats    = false
